### ISSUE TITLE
Feature: User can view a map with markers for specified locations

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a map with markers for recommended activities/locations

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see a Google Map component with markers that specify what kind of category a recommended location fits under (hiking, water activities, snow activities, misc)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="422" alt="Screenshot 2022-12-30 at 10 16 04 AM" src="https://user-images.githubusercontent.com/110082070/210100673-f3006f9c-350a-4184-80e9-870a0148bca2.png">
<img width="1198" alt="Screenshot 2022-12-30 at 10 16 46 AM" src="https://user-images.githubusercontent.com/110082070/210100719-9d4a9c0c-959e-45cb-b369-f4fe49b72bcf.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include tables and fields created earlier using DBdesigner 
- [x] Update `data.sql` to add required data for recommended locations (placeId, category, name)
- [x] Duplicated .env.example file
- [x] Alter duplicated file contents to include API key needed to access Google Maps / Places API 
- [x] Create PostgreSQL database with `createdb` command

### ☁️ Server Tasks

- [x] Build Express.js server inside `server/index.js`
- [x] Import both error middleware components
- [x] Write SQL queries to obtain location information from database, and store content in a new object
- [x] Use coordinates retrieved from database to `fetch` 
- [x] Update `server/index.js` to respond to client indicating a successful request made to the web server
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add Google Maps component to app and specify initial center and zoom levels
- [x] Fetch location data from server and pass it to the Google Maps component as props
- [x] Create a component to represent a marker on the map
- [x] Pass component for marker props containing latitude, longitude, and category
- [x] Add JSX code using Bootstrap classes following UI design from Figma
- [x] Add Bootstrap tabs and custom CSS classes to make webpage responsive for mobile and desktop view
- [x] Add sample card components inside tab content
- [x] Customize the appearance of the map and markers using API and CSS, using different icons or colors for different categories
- [x] Implement a dropdown menu or other UI element to allow the user to select a category to filter the locations by
- [x] Write code to handle the user's selection and update the map accordingly by making a new request to the server with the updated category parameter

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
