### ISSUE TITLE
Feature: User can view route details in new window for Google Maps URL

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be directed to a new window to view their selected route and directions in the official Google Maps website.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When at least two locations are pinned and route options are shown in the directions panel, user can click `See Route in Google Maps` to be directed to a Google Maps url containing the coordinates for the pinned locations.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update anchor component in the dropdown menu of DirectionsPanel to include `href` attribute to link user to Google Maps in a new tab.
- [x] Ensure new Google Maps window resulted in a route between two locations selected by user via coordinates
- [x] Adjust URL to search for multiple coordinates
- [x] Add coordinates of newly pinned location to end of array in value of a comma separated string
- [x] Add coordinate pairs as template literal values inside Google Maps URL

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
