### ISSUE TITLE
Feature: User can save created route

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click `Save Route` button to create an easily accessible representation of the newly created route and save it as a new card within `My Routes` tab. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once a route has been established, the user can save the order of the locations within the `My Routes` tab, which can list out new route entries similarly to how the previous two tabs listed out locations. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="289" alt="Screenshot 2023-01-02 at 9 53 10 PM" src="https://user-images.githubusercontent.com/110082070/210306021-f9173a2c-aa08-46a0-a8ba-e20e02c23d00.png">

<img width="621" alt="Screenshot 2023-01-02 at 9 54 20 PM" src="https://user-images.githubusercontent.com/110082070/210306118-710e8330-0120-4a7f-8a7f-24527273b5b1.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` and replace both 'route' related tables with new tables "routes" and "routeLocations"
- [x] Ensure that routeIds are incremented as a primary key in "routes" table, so each routeId is unique for every submission and user.
- [x] Ensure that routeIds are inserted in multiple rows with user inputted myListItemsIds
- [x] Ensure the correct order of user pinned locations are reflected in the order the rows are inserted

### ☁️ Server Tasks

- [x] Update `server/index.js` to insert multiple rows into both "routes" and "routeLocations" table with single POST request
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create initial routeName variable to pass into fetch request in dropdown menu component 
- [x] Update onClick attribute of existing Save Route anchor in dropdown menu with callback function that sends a single `fetch()` call to '/api/routes'
- [x] Use response to set state in dropdown menu component
- [x] Use state value to pass as props to home component

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
