### ISSUE TITLE
Feature: User can rename saved route entry

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit the name for a saved route entry after it has been created. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a route is saved, the default name will just include the number in which the route was created. For example, the first route created will have a name of `New Route #1`. User can double-click on route name/title and edit it to their liking. 

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` POST requests to '/api/routes' to use new routeName value, instead of previous method of using routeId.
- [x] Ensure response to client includes previously stored routeName value to then use while rendering the JSX for each SavedRoute component.
- [x] Update `server/index.js` to handle a new PUT request to update a certain routeId's corresponding routeName within the database. 
- [x] Respond to client with new object once successful PUT request is complete

### ⚡ Client Tasks

- [x] Update 'Save Route' button inside Directions Panel offcanvas, to trigger a new, separate offcanvas component with an input field for a route name, and title "Save Route?"
- [x] Adjust POST request and fetch() call to run when the 'Save' button inside the modal is clicked. 
- [x] Ensure that offcanvas components are dismissed properly utilizing Bootstrap properties, with only one open at a time. 
- [x] Import `useRef` and utilize it to keep track of the input value inside the Save Route form
- [x] Utilize user typed name as a property within the POST request object, to be stored in database with ids.
- [x] Ensure routeName is 
- [x] Add an editing icon to be rendered alongside each routeName value of each Saved Route Component.
- [x] Add onClick event listeners to editing icon to trigger a new `Edit Route` modal. 
- [x] Take in response from successful PUT request to utilize new route name in JSX immediately in DOM

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
