### ISSUE TITLE
Feature: User can click on saved route entry to render new map

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a route's custom map and visual route in 'My Routes' tab by clicking on a saved route.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on a previously saved route entry and render each route's custom map inside `My Routes` tab

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="291" alt="Screenshot 2023-01-02 at 9 56 03 PM" src="https://user-images.githubusercontent.com/110082070/210306267-30c7fade-79b6-422b-b7e7-90bbde3f79d2.png">
<img width="621" alt="Screenshot 2023-01-02 at 9 55 40 PM" src="https://user-images.githubusercontent.com/110082070/210306233-d2f213e6-9949-41d0-82de-3144c2f24324.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update Saved Route component to include a pointer when user hovers over it. 
- [x] Update each component to have an onClick event handler to respond to user with necessary locationIds.
- [x] Ensure ids obtained from props can be utilized in new functions passed to Saved Route components as props. 
- [x] Pass values obtained from Saved Route component to set state in parent Home component. 
- [x] Ensure switching between tabs and info views are consistent with previous methods. 
- [x] Condense information given in Routes tab with collapsable components. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
