### ISSUE TITLE
Feature: User can remove a saved route entry

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a saved route entry and its contents within the `My Routes` tab

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a saved route entry is selected within `My Routes`, a `Delete Route` button will appear. A modal will appear, asking user to confirm choice. If confirmed, the saved route entry and its content is removed from `My Routes` tab. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="617" alt="Screenshot 2023-01-02 at 9 45 49 PM" src="https://user-images.githubusercontent.com/110082070/210305473-8363729f-e7a0-46fd-bab7-38a985b0c207.png">
<img width="615" alt="Screenshot 2023-01-02 at 9 46 03 PM" src="https://user-images.githubusercontent.com/110082070/210305493-796e9197-e74d-4ddc-9140-f86ecbe0cf5e.png">
<img width="615" alt="Screenshot 2023-01-02 at 9 46 26 PM" src="https://user-images.githubusercontent.com/110082070/210305519-92f826ab-9d4a-4cfd-96f9-f7a00c2a3690.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include new route handler for DELETE requests
- [x] Ensure route handler is able to delete all rows from both "routes" and "routeLocations" tables with specific routeId parameter

### ⚡ Client Tasks

- [x] Update Edit Form component to include a new `Delete Route` button within the modal that appears
- [x] Include onClick event handler for `Delete Route` button to trigger a second modal to confirm deletion.
- [x] Ensure that first modal is closed when confirmation modal is triggered. 
- [x] Obtain routeId to use in DELETE request to database
- [x] Within chained `.then` statements, ensure that viewingIds state is also set to `false` when routeId is removed from database.
- [x] Ensure the locationIds included in deleted route are not deleted from myListItemsIds table, just the routes and route-locations tables. Selecting only the rows with specified routeId
- [x] Ensure homeRoutes state is updated in Home component using server response with deleted route info.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
