### ISSUE TITLE
Feature: User can filter markers on map by clicking on categories

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can filter which markers are shown on the map by selecting categories that describe locations/activities from a dropdown menu.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Inside the Places tab, users will be able to open a drop down menu that lists the different types of locations that are recommended to visit. When a category is selected, the card component will replace the previous listed locations with those that match that category.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/110082070/213803867-e7cb37d6-e259-4606-8ead-ce62dd19c6cf.png)

![image](https://user-images.githubusercontent.com/110082070/213803388-45d48dcd-3f5b-4e8b-b398-2943a6148d7a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update 'schema.sql' to include additional location fields in order to further test and prevent exceeding query limits when using the Google Places and Google Maps API by making too many requests in quick succession.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a new route hander that includes each category's value (Ex. get('api/locations/{Category Name}')
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a Bootstrap dropdown menu component
- [x] Ensure that default activeItem state is set to 'All Categories'
- [x] Ensure that clicking a button option for another category changes the activeItem state and primary dropdown label.
- [x] Within home.jsx, define a 'onSelect()' function within the props for DropDownMenu component
- [x] Define with one parameter 'selectedCategory' and use it to set 'place' state in home.jsx
- [x] Back in dropdownmenu.jsx, pass string value of category as an argument for props.onSelect()

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
