### ISSUE TITLE
Feature: User can sign up for access

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#25]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up for an account with their email address, a new username, and password. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the application is first loaded, the user is now sent to a log in screen that contains a form to take a user's email or username, along with their password. Underneath is a `Sign Up` button for new users to create an account with all three of the previous fields. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Install express-validator for sanitization and validation purposes
- [x] Use methods from the express-validator middleware within sign-in and sign-up route handlers
- [x] Ensure user input values are sanitized and validated for server side code within array of middleware functions before being processed by route handler functions. 

### ⚡ Client Tasks

- [x] Update App component to be called as a functional component to utilize React state hooks.
- [x] Add new state hook to conditionally render components within App component
- [x] Fetch required user info for access using previously created sign in route handler. 
- [x] Show input is invalid when credentials are rejected
- [x] If valid and user info is generated, set state to trigger Home component to render
- [x] Create sign out button to reset state to default logged out state.
- [x] Create new state in App to conditionally render Sign Up component if button in sign in form is clicked
- [x] Show that input is invalid if a valid email is not used
- [x] Show that input is invalid if a username value already exists
- [x] Show that input is invalid if a password is not long enough and/or does not include a special character.
- [x] Create button to toggle sign up state and switch between forms.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
