### ISSUE TITLE
Feature: User can access with guest limitations

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#26]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User skip account creation to access the application with feature limitations. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will have the option to create an account to utilize all features of the application. Features related to user interaction with the database will require account creation. Details provided by the Google Places API related to reviews and photos will still be accessible with guest access.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

https://user-images.githubusercontent.com/110082070/229942551-e789fc9d-d2dd-4607-976f-137014dc314f.mov

https://user-images.githubusercontent.com/110082070/229942558-38636d6d-7f2c-4bb8-aedb-9ca82eba9a18.mov

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to include full list of locations before deployment

### ⚡ Client Tasks

- [x] Create a link for user to click and access site with guest limitations by passing props value from App component to Home component.
- [x] Update Home component to assign value of verified user token to accessToken variable. 
- [x] Update useEffect hook to check for a valid user token before retrieving relevant information from database. If invalid, useEffect hook will only render place details and markers.
- [x] Update My List tab and its components to show alert informing guest account creation is required for further access
- [x] Update Routes tab and its components to show alert informing guest account creation is required for further access

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
