### ISSUE TITLE
Feature: User can select place of interest to add to 'My List'

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can select locations of interest to add into a separate `My List` tab to store and create new routes from. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The `My List` tab will be an empty list by default, but will be able to store locations that the user wishes to save to view at another time, or to later on use in the creation of new routes that will populate visually on the map with markers. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

https://user-images.githubusercontent.com/110082070/214745182-a70f1a27-91e0-43dd-ad23-0f455d94a2f6.mov

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Create new post route '/api/auth/sign-up' to implement account creation
- [x] Create new post route '/api/auth/sign-in' for token creation when user signs in 
- [x] After authorization and token creation, create new post route that stores locationId and userId to the "myListItems" table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add event listener on ‘add’ button in LocationCards that are displayed in Places tab
- [x] In callback for event listener, use the locationId of the clicked location card as an argument to be used in a function based by parent’s props.
- [x] In same callback, add the locationId into a post request for route '/api/mylist' to store locationId in database.
- [x] Create new state ‘addedLocations’ with useState React hook.
- [x] In home.jsx, set addedLocation state with locationId obtained from LocationCard component
- [x] Within empty tab, create a new JSX tree containing data for new location cards.
- [x] Make sure only the locations including any locationIds selected by user are being rendered in new tab. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
