### ISSUE TITLE
Feature: User can view extra details about location 

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can expand location cards to view extra details. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking the `info` button will render new components with data fetched from the Google Places API, including a list of user reviews and any available photos. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update Google Places API Details request to include field for user reviews.
- [x] Adjust Each Card component so it renders extra details about each location, to be called in `home.jsx`
- [x] Include a carousel that switches between available photos retrieved from Google Places API.
- [x] Map through and render list of user reviews below photo carousel. 
- [x] Update 'onClick' event listener on 'info' button for each location card to render ExtraDetails component. 
- [x] Make sure JSX for extra details is being conditionally rendered in Places tab, replacing the list of smaller location cards when clicked. 
- [x] Include new state in `home.jsx` that tracks whether a location's details are being viewed or not with a default boolean value of `false`. 
- [x] Create function that listens to previous state and replaces all markers shown on map with the one for the selected location.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
