### ISSUE TITLE
Feature: User can delete place of interest from ‘My List’ 

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove any previously added locations from created list in 'My List` tab

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Inside the card components within the `My List` tab, there will be a `remove` icon that the user can click to reveal a modal with buttons to confirm or cancel deletion. This won't alter anything inside the 'Places' tab, but will remove that specific location from 'My List' using its unique `myListItemsId`

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="718" alt="myList figma" src="https://user-images.githubusercontent.com/110082070/216792757-06052f1d-74d5-4c2f-a675-66f14444e0d3.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a route handler for `delete` requests
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Adjust existing `get` requests to return `myListItemsId` as well for each added location
- [x] Adjust `post` route handler to return same fields as previous `get` request.

### ⚡ Client Tasks

- [x] Update fetch() in `home` component to set `addedLocations` state with full response, including `myListItemsId` from server instead of just the `locationId`.
- [x] Adjust existing fetch() call for `post` request. Instead of setting `addedLocations` with `locationId` when an 'add' button is clicked, set state within `.then()` using a successful post response which matches the new format for `addedLocations` state.
- [x] Pass required database information (matching myListItemsId & locationId) as props for `EachCard` component.
- [x] Create new props function `removeCard()`
- [x] Include a new minus sign icon to indicate where a user should click to remove location from My List tab.
- [x] Add click event listener on icon that calls  `removeCard()` with clicked location's 'myListItemsId' as single argument
- [x] Utilize clicked location's `myListItemsId` as params within a new fetch() call for a `delete` request. 
- [x] After successful `delete` request and converting JSON response, use deleted location object that was sent as response from server, and filter out said location from existing `addedLocations` array. 
- [x] Use newly filtered array to set `addedLocations` state.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
