### ISSUE TITLE
Feature: User can pin location on an empty map

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select a location within `My List` to pin a marker on a new, empty map

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click `Pin` button inside user created list of locations, and see a marker for that location appear on a newly rendered map component that is shown when `My List` tab is opened.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="289" alt="Screenshot 2023-01-02 at 9 51 02 PM" src="https://user-images.githubusercontent.com/110082070/210305851-80225c09-2098-4d55-8ba2-c26d01416731.png">
<img width="621" alt="Screenshot 2023-01-02 at 9 51 25 PM" src="https://user-images.githubusercontent.com/110082070/210305885-d15d6efc-3f97-4190-b894-940318955445.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update viewingIds state to be set with array of IDs.
- [x] Ensure extra details view is not changed with changes to previous state.
- [x] Add event handler for clicking Pin button to add IDs to viewingIds state in order of which locations were clicked first.
- [x] Create new prevList state to retain pinned markers when switching between My List and Places tabs.
- [x] Add event handler for clicking Place tab to set viewingIds state back to default state when switching between My List tab, and to set prevList state with previous viewingIds state.
- [x] Add event handler for clicking My List tab to set viewingIds with retained prevList.
- [x] Add Bootstrap alert messages to My List tab that render conditionally if any locations are added by user yet. 
- [x] Adjust MapMarkers component to render newly clicked pins as they are clicked by user. 
- [x] Ensure that map is empty when no locations are pinned / by default when page loads.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
