### ISSUE TITLE
Feature: User can view a route (with directions) between all newly pinned locations

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select multiple locations to pin on map, and view a clear, styled route between all selected locations.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see a distinct route on the map to give directions that can be taken between those selected locations.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="287" alt="image" src="https://user-images.githubusercontent.com/110082070/210305593-7f458bc1-bcbf-4a94-81bb-0f3a9fe9b173.png">
<img width="621" alt="image" src="https://user-images.githubusercontent.com/110082070/210306414-69b1d977-7aa8-4543-b83c-6f543bbd7aed.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update MapMarkers component to render a new route created with Google Directions API.
- [x] Only include route creation after 2 or more locations are pinned by user.
- [x] Create new mappedIds array with value of `this.props.place` array that only includes location objects of the locations with the same ids in the viewingId array.
- [x] Ensure mappedIds array is in the same order as viewingIds array.
- [x] Refactor `home` component to render card components in My List tab to appear in order of user addition, similar to how `mappedIds` array works for route order. 
- [x] Add modal to contain Google Directions API 'panel' response containing written driving directions and route details. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
