### ISSUE TITLE
Feature: User can see pinned locations listed out in new tab

### ISSUE THREAD

**Issue by jamesdae** [jamesdae/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Along with the visual representation of the route, the user can see the cards for each pinned location inside the `My Routes` tab.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Whenever a location is pinned from `My List`, its card is added to a new list in `My Routes` tab named `New Route`. This tab where custom routes will later be saved, and any additional route details

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="289" alt="Screenshot 2023-01-02 at 9 50 11 PM" src="https://user-images.githubusercontent.com/110082070/210305791-f64a5798-d443-440a-aaa9-d15beab404bf.png">
<img width="622" alt="Screenshot 2023-01-02 at 9 57 03 PM" src="https://user-images.githubusercontent.com/110082070/210306339-7c670d81-7080-4879-924e-e2a92e9af656.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update home component to conditionally render EachCard components in empty My Routes Tab.
- [x] Ensure My Routes tab is rendering only the locations that have been pinned by user (viewingIds & mappedIds)
- [x] Ensure cards are being removed from My Routes tab as soon as they are deleted from database
- [x] Ensure Route Options button is rendered in My Routes tab under same conditions as it appears in My List tab. 
- [x] Ensure cards are being removed from My Routes tab as soon as `Clear Pins` button is pressed (when `viewingIds === false`)
- [x] Update EachCard component conditionally render a new 'Unpin' button for cards in My Routes tab. 
- [x] Add event handler for Unpin button clicks to remove that ID from viewingIds state in Home component.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
